#!/bin/sh

set -e

BIN="$(dirname "$0")"
COMMAND="$1"
: ${JULIA:=julia}

if [ -z "$COMMAND" ]; then
    echo "usage: $(basename "$0") <command> [args...]"
    echo
    echo "commands:"
    for TOOL in $(cd "$BIN"; echo */run.jl); do
        echo "  ${TOOL%/run.jl}"
    done
    exit 0
fi

TOOL="$BIN/$COMMAND"

"$JULIA" --project="$TOOL" -- - <<JULIA_VERSION_CHECK
    import Pkg
    REQUIRED = Pkg.Versions.semver_spec(
        Pkg.TOML.parse(read(Pkg.project().path, String))["compat"]["julia"]
    )
    if !(VERSION in REQUIRED)
        @error "Incompatible Julia version" CURRENT=VERSION REQUIRED
        exit(1)
    end
JULIA_VERSION_CHECK

# Check if `]instantiate` needs to be run for the tool environment's
# `Manifest.toml`. If so, run it and take note of the instantiated state and
# instantiating Julia version (unless the directory is write-protected, which
# is not really a problem since `]instantiate` is idempotent, though it will
# add latency).
JULIA_VERSION="$("$JULIA" --version)"
INSTANTIATED_WITH="$(
    cat "$TOOL"/instantiated_with.version 2>/dev/null || true
)"
if
    [ "$JULIA_VERSION" != "$INSTANTIATED_WITH" ] || \
    ! cmp --silent "$TOOL/Manifest.toml" "$TOOL/Instantiated.toml"
then
    >&2 echo \
        "Info: '$COMMAND' Julia environment may be stale," \
        "running \`]instantiate\`..."
    (
        set -x
        "$JULIA" --project="$TOOL" \
            -e 'import Pkg; Pkg.instantiate(verbose = true)'
    )
    echo "...done."
    cp "$TOOL/Manifest.toml" "$TOOL/Instantiated.toml" 2>/dev/null || true
    "$JULIA" --version 2>/dev/null >"$TOOL/instantiated_with.version" || true
fi

shift

exec "$JULIA" --project="$TOOL" "$TOOL/run.jl" "$@"
