#!/bin/sh

set -e

BIN="$(dirname "$0")"
COMMAND="$1"
: ${JULIA:=julia}

"$JULIA" --project="$BIN" -- - <<JULIA_VERSION_CHECK
    import Pkg
    REQUIRED = Pkg.Versions.semver_spec(
        Pkg.TOML.parse(read(Pkg.project().path, String))["compat"]["julia"]
    )
    if !(VERSION in REQUIRED)
        @error "Incompatible Julia version" CURRENT=VERSION REQUIRED
        exit(1)
    end
JULIA_VERSION_CHECK

# Check if `]instantiate` needs to be run for the current `bin/Manifest.toml`.
# If so, run it and take note of the instantiated state and instantiating Julia
# version (unless `bin` is write-protected, which is not really a problem since
# `]instantiate` is idempotent, though it will add latency).
JULIA_VERSION="$("$JULIA" --version)"
INSTANTIATED_WITH="$(cat "$BIN"/instantiated_with.version 2>/dev/null || true)"
if
    [ "$JULIA_VERSION" != "$INSTANTIATED_WITH" ] || \
    ! cmp --silent "$BIN/Manifest.toml" "$BIN/Instantiated.toml"
then
    >&2 echo \
        "Info: Julia environment may be stale, running \`]instantiate\`..."
    (
        set -x
        "$JULIA" --project="$BIN" \
            -e 'import Pkg; Pkg.instantiate(verbose = true)'
    )
    echo "...done."
    cp "$BIN/Manifest.toml" "$BIN/Instantiated.toml" 2>/dev/null || true
    "$JULIA" --version 2>/dev/null >"$BIN/instantiated_with.version" || true
fi

if [ -z "$COMMAND" ]; then
    echo "usage: $(basename "$0") <command> [args...]"
    echo
    echo "commands:"
    for SCRIPT in $(cd "$BIN"; echo *.jl); do
        echo "  ${SCRIPT%.*}"
    done
    echo "  julia"
    exit 0
fi

shift

if [ "$COMMAND" = "sysimage" ]; then
    # We special-case the `sysimage` command to itself always use the default
    # sysimage to avoid trouble in case of broken or stale sysimages, e.g.
    # when recompiling. But we still would like it to be as fast as possible,
    # so to reduce latency in the non-compiling branches, we tell Julia to
    # reduce compilation. This especially applies to `sysimage locate`,
    # which gets called for all other commands to resolve the sysimage
    # to use.
    # However, since `sysimage compile` is a longer-running operation, we
    # specifically exclude it from reduced Julia compilation.
    case "$@" in
        *compile*) exec "$JULIA" --project="$BIN" "$BIN/sysimage.jl" "$@";;
        *) exec "$JULIA" --project="$BIN" --compile=min \
            "$BIN/sysimage.jl" "$@";;
    esac
elif [ "$COMMAND" = "julia" ]; then
    exec "$JULIA" --project="$BIN" --sysimage="$("$0" sysimage locate)" "$@"
else
    exec "$JULIA" --project="$BIN" --sysimage="$("$0" sysimage locate)" \
        "$BIN/$COMMAND.jl" "$@"
fi
